### ISSUE TITLE
Column headings meaningless about which ZIP file is "1" and which ZIP file is "2"

### ISSUE THREAD

**Issue by sandraros** [sandraros/zip-diff#2]
Green color means the file inside the ZIP file is added, so we can deduce that it's added in "2" (date, time and size not empty), but which ZIP files correspond to "1" and "2" from user perspective is difficult to say (except that technically "1" is the "old" ZIP file and "2" is the "new" ZIP file).

![image](https://user-images.githubusercontent.com/34005250/149659809-bf2c5a25-947c-4fe6-b739-aaeea5eff861.png)

Code to reproduce:
```abap
REPORT z_zip_diff_demo2.
DATA zip_diff TYPE REF TO zcl_zip_diff_viewer2.
PARAMETERS dummy.
AT SELECTION-SCREEN OUTPUT.
  IF zip_diff IS NOT BOUND.
    zip_diff = NEW #( cl_gui_container=>screen0 ).
    DATA(zip_old) = NEW cl_abap_zip( ).
    zip_old->add( name = 'changed.txt' content = cl_abap_codepage=>convert_to( 'hello world' ) ).
    zip_old->add( name = 'deleted.txt' content = cl_abap_codepage=>convert_to( 'I was deleted' ) ).
    DATA(zip_new) = NEW cl_abap_zip( ).
    zip_new->add( name = 'added.txt' content = cl_abap_codepage=>convert_to( 'I was added' ) ).
    zip_old->add( name = 'changed.txt' content = cl_abap_codepage=>convert_to( 'hey world' ) ).
    zip_diff->diff_and_view( zip_old = zip_old zip_new = zip_new ).
  ENDIF.
```

Proposal: add the possibility to give a functional name to each ZIP file. For instance, "Web Repository .zip file" for "1"/"old" ZIP file, and "Demo program .zip file" for "2"/"new" ZIP file:
- expected result:
  ![image](https://user-images.githubusercontent.com/34005250/149661365-ac8b5c13-cacb-453a-81f7-fae865674045.png)
- code:
  ```abap
  REPORT z_zip_diff_demo2.
  DATA zip_diff TYPE REF TO zcl_zip_diff_viewer2.
  PARAMETERS dummy.
  AT SELECTION-SCREEN OUTPUT.
    IF zip_diff IS NOT BOUND.
      zip_diff = NEW #( cl_gui_container=>screen0 ).
      DATA(zip_old) = NEW cl_abap_zip( ).
      zip_old->add( name = 'changed.txt' content = cl_abap_codepage=>convert_to( 'hello world' ) ).
      zip_old->add( name = 'deleted.txt' content = cl_abap_codepage=>convert_to( 'I was deleted' ) ).
      DATA(zip_new) = NEW cl_abap_zip( ).
      zip_new->add( name = 'added.txt' content = cl_abap_codepage=>convert_to( 'I was added' ) ).
      zip_old->add( name = 'changed.txt' content = cl_abap_codepage=>convert_to( 'hey world' ) ).
      zip_diff->diff_and_view( title_old = 'Web Repository .zip file' title_new = 'Demo program .zip file'
                               zip_old = zip_old zip_new = zip_new ).
    ENDIF.
  ```

**Comment by AndreaBorgia-Abo** [comment]
I'll think about it and let you know

**Comment by sandraros** [comment]
Fixed by #3

**Comment by AndreaBorgia-Abo** [comment]
So, using the Quartz (default?) theme on 7.70 Windows GUI makes it extremely hard to tell which flag corresponds to which file, one flag is apparently dark green and the other apparently dark blue :(
![immagine](https://user-images.githubusercontent.com/25269970/151515349-33ffad0e-09a7-4e13-9604-12b6ce789786.png)

**Comment by sandraros** [comment]
Thanks! Too bad, then let's choose one flag icon and one non-flag icon...

**Comment by AndreaBorgia-Abo** [comment]
Yup, new icons can be easily distinguished:
![immagine](https://user-images.githubusercontent.com/25269970/152636286-222510f2-b828-473a-bef5-7af19b571fdd.png)

thank you.
