### ISSUE TITLE
Z_ZIP_DIFF_DEMO2 dummy label and checkbox visible in JavaGUI

### ISSUE THREAD

**Issue by AndreaBorgia-Abo** [sandraros/zip-diff#4]
![immagine](https://user-images.githubusercontent.com/25269970/151511967-0d5b5c09-b7a4-4b38-8837-cbc8b99cff4b.png)

Issue detected with Java SAPGUI 7.70 rev4, while Windows GUI 7.70 patch 4 seems fine.
Probably an underlying GUI issue, not ZIP_DIFF specific.

**Comment by sandraros** [comment]
Could you check if the latest fix (#8) solves the issue? Thanks.

**Comment by AndreaBorgia-Abo** [comment]
It didn't but the fix is simple, I've left a comment there.

**Comment by sandraros** [comment]
Weird. I was pretty sure it would solve the issue by deactivating the field (I confirm that it should be `screen-active = '0'` (off), this removes the field from the screen).

**Comment by AndreaBorgia-Abo** [comment]
"screen" is not the working area of the loop, "screen_field" is

**Comment by sandraros** [comment]
Thanks, my bad! Fixed by [this](https://github.com/sandraros/zip-diff/commit/83b2b09201d874f9d4c9da940e5f1a1ab155bfbb). Could you test again please?

**Comment by AndreaBorgia-Abo** [comment]
It works, I checked the change before commenting. Go ahead.
